[package]
name = "vulnerable-rust"
version = "0.1.0"
authors = ["Prash G <prash@clouddefense.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "=0.13.5"
failure = "0.1"
ammonia = "2.0.0"